# Generated by Django 5.2.8 on 2025-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, help_text='Ej: Rojo,Azul,Negro,Blanco', max_length=200),
        ),
    ]
